# netlify.toml

[[rewrites]]
  from = "/help/*"
  to = "https://chatbase.co/{29XIzccAN0TJQUrMfLuJN}/help/:splat"
  status = 200 # A 200 status indicates a rewrite, not a redirect

[[rewrites]]
  from = "/help"
  to = "https://chatbase.co/{29XIzccAN0TJQUrMfLuJN}/help"
  status = 200
